### ISSUE TITLE
重新渲染时（options未改变），词云会重绘

### ISSUE THREAD

**Issue by xiaoweiSun** [ecomfe/echarts-wordcloud#108]
我的页面会经常重新渲染，但options包括data都未改变，词云会重绘（有重新渲染的动画），但其他echarts组件看起来没有这种情况

**Comment by sky185959** [comment]
我也遇到词云重绘的情况，不知道你解决了没有？

**Comment by weimanqing** [comment]
我也遇到这样的问题，请问解决了吗？
