### ISSUE TITLE
在绘制期间，如销毁图形，则导致浏览器比较卡

### ISSUE THREAD

**Issue by FlowerBirds** [ecomfe/echarts-wordcloud#11]
1.当数据量较大，绘制时间较长；
2.在绘制期间，调用图形的dispose方法进行销毁，则会出现问题；

具体调试结果如下：
当正在绘制时，sendEvent方法发送wordclouddrawn事件，该事件会将Text添加到Storage中去，调用storage.addToMap方法。在调用图形的dispose方法时，同时也会调用storege.dispose方法，而Storage会将自身存的对象清空，elements = null，如再调用addTomap方法时，则会this.elements[el.id] = el，这句会报错，因为elemets已经为null；

以上的错误会持续发生，而不会因为报错而终止；最终会导致浏览器比较卡，目前分析到这块。

**Comment by pissang** [comment]
同 https://github.com/ecomfe/echarts-wordcloud/issues/12 ，已修复

**Comment by FlowerBirds** [comment]
非常感谢

**Comment by FlowerBirds** [comment]
非常感谢
