### ISSUE TITLE
同问：5.x版本会报此错误，并且水球图echarts-liquidfill.min.js也会报错

### ISSUE THREAD

**Issue by frienkiss** [ecomfe/echarts-wordcloud#111]
同问：5.x版本会报此错误，并且水球图echarts-liquidfill.min.js也会报错

_Originally posted by @frienkiss in https://github.com/ecomfe/echarts-wordcloud/issues/92#issuecomment-781199871_

**Comment by pissang** [comment]
wordcloud 和 echarts 都更新到最新版本呢

**Comment by frienkiss** [comment]
嗯嗯，搞定了，缓存没拿到最新的哈哈哈，谢谢
