### ISSUE TITLE
Resize窗口时，重绘出现好几个一样的字符云重叠。

### ISSUE THREAD

**Issue by SangoYu** [ecomfe/echarts-wordcloud#12]
字符云图绘完之后，Resize窗口时，很大几率会出现同样的字符叠很多层，echarts的官方词云图里就可以重现。
请确认。
![image](https://cloud.githubusercontent.com/assets/12133627/20429951/9e9d4e9a-adcc-11e6-825e-07052bb93e29.png)

**Comment by jarben** [comment]
I can also confirm this issue, seems like canvas is not cleared when setting options again, my result is this: 
![image](https://cloud.githubusercontent.com/assets/561365/20858219/61b60a74-b940-11e6-9044-58f76f8cc7cb.png)

**Comment by jarben** [comment]
Looks like wordclouddrawn event is attached again after resize + previous canvas elements not destroyed properly?

![image](https://cloud.githubusercontent.com/assets/561365/20859127/34a0dda0-b956-11e6-8940-4a3ae3f8e8d4.png)

Is there any layout destroy mechanism where canvas elements can be destroyed? 

This assumption might be completely wrong:)

**Comment by jarben** [comment]
Attaching demo code that can be tested in the examples editor
[world-cloud-issue.zip](https://github.com/ecomfe/echarts-wordcloud/files/628824/world-cloud-issue.zip)

This happens after resize: 

![image](https://cloud.githubusercontent.com/assets/561365/20859183/e1996e9a-b957-11e6-8c68-b85b6531b74d.png)

**Comment by jarben** [comment]
Awesome, thanks @pissang , tested, works ok!
