### ISSUE TITLE
a.List is not a constructor

### ISSUE THREAD

**Issue by hzs1254** [ecomfe/echarts-wordcloud#16]
Uncaught TypeError: a.List is not a constructor
    at r.getInitialData (echarts-wordcloud.min.js:1)
    at r.init (echarts.min.js:10)
    at r.n [as constructor] (echarts.min.js:10)
    at r [as constructor] (echarts.min.js:11)
    at new r (echarts.min.js:11)
    at r.<anonymous> (echarts.min.js:23)
    at p (echarts.min.js:1)
    at r.e (echarts.min.js:23)
    at Function.t.topologicalTravel (echarts.min.js:12)
    at r.mergeOption (echarts.min.js:23)

我的配置:

var  option2 = {
            tooltip: {},
            series: [ {
                type: 'wordCloud',
                gridSize: 2,
                sizeRange: [12, 50],
                rotationRange: [-90, 90],
                shape: 'pentagon',
                width: 600,
                height: 400,
                textStyle: {
                    normal: {
                        color: function () {
                            return 'rgb(' + [
                                    Math.round(Math.random() * 160),
                                    Math.round(Math.random() * 160),
                                    Math.round(Math.random() * 160)
                                ].join(',') + ')';
                        }
                    },
                    emphasis: {
                        shadowBlur: 10,
                        shadowColor: '#333'
                    }
                },
                data: [
                    {
                        name: 'Sam S Club',
                        value: 10000,
                        textStyle: {
                            normal: {
                                color: 'black'
                            },
                            emphasis: {
                                color: 'red'
                            }
                        }
                    },
                    {
                        name: 'Macys',
                        value: 6181
                    },
                    {
                        name: 'Amy Schumer',
                        value: 4386
                    },
                    {
                        name: 'Jurassic World',
                        value: 4055
                    },
                    {
                        name: 'Charter Communications',
                        value: 2467
                    },
                    {
                        name: 'Chick Fil A',
                        value: 2244
                    },
                    {
                        name: 'Planet Fitness',
                        value: 1898
                    },
                    {
                        name: 'Pitch Perfect',
                        value: 1484
                    },
                    {
                        name: 'Express',
                        value: 1112
                    },
                    {
                        name: 'Home',
                        value: 965
                    },
                    {
                        name: 'Johnny Depp',
                        value: 847
                    },
                    {
                        name: 'Lena Dunham',
                        value: 582
                    },
                    {
                        name: 'Lewis Hamilton',
                        value: 555
                    },
                    {
                        name: 'KXAN',
                        value: 550
                    },
                    {
                        name: 'Mary Ellen Mark',
                        value: 462
                    },
                    {
                        name: 'Farrah Abraham',
                        value: 366
                    },
                    {
                        name: 'Rita Ora',
                        value: 360
                    },
                    {
                        name: 'Serena Williams',
                        value: 282
                    },
                    {
                        name: 'NCAA baseball tournament',
                        value: 273
                    },
                    {
                        name: 'Point Break',
                        value: 265
                    }
                ]
            } ]
        };

**Comment by pissang** [comment]
什么版本 echarts，怎么引入的，请具体描述你的问题

**Comment by hzs1254** [comment]
<script src="assets/library/echarts/echarts.min.js"></script> 
 -version:3.2.2
<script src="assets/library/echarts/echarts-wordcloud.min.js"></script>
-version:1.0.1
谢谢

**Comment by pissang** [comment]
echarts 更新到最新版本试下

**Comment by hzs1254** [comment]
我的问题，打扰了，非常感谢！
