### ISSUE TITLE
echarts5.4.2 版本 和 echarts-wordcloud2.1.0 版本 兼容报错了！！！

### ISSUE THREAD

**Issue by GreatHonour** [ecomfe/echarts-wordcloud#161]
![image](https://github.com/ecomfe/echarts-wordcloud/assets/25587991/a72d626f-e9c3-43b8-a535-4ef12ebdf037)
![image](https://github.com/ecomfe/echarts-wordcloud/assets/25587991/786dba07-2af3-4f5e-8bf9-d8463821a4da)

WordCloudView.js:14 Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'ondraw')
    at ExtendedClass.render (WordCloudView.js:14:1)
    at Task.progress (Chart.js:233:1)
    at Task._doProgress (task.js:187:1)
    at Task.perform (task.js:153:1)
    at eval (echarts.js:1824:1)
    at GlobalModel.eval (Global.js:654:1)
    at Array.forEach (<anonymous>)
    at each (util.js:205:1)
    at GlobalModel.eachSeries (Global.js:651:1)
    at renderSeries (echarts.js:1812:1)

**Comment by GreatHonour** [comment]
按需引入问题

**Comment by Mister-Hope** [comment]
Hi bro, could you share some detailed explanation? I encountered the same problem. But I think I am importing the whole package through `import(/* webpackChunkName: "echarts" */ "echarts")`.

I have the exact same error stack as yours:

<img width="520" alt="image" src="https://github.com/ecomfe/echarts-wordcloud/assets/33315834/f684b574-b43d-4ac7-9ecf-5a01a517badf">

**Comment by Paper-Dragon** [comment]
Is there any new process?

**Comment by jevin98** [comment]
Make sure that the echarts-wordclound warehouse is successfully introduced before executing the echarts.init method.
