### ISSUE TITLE
I met a error： [ECharts] Unknown series wordCloud

### ISSUE THREAD

**Issue by ZhuJingLe** [ecomfe/echarts-wordcloud#174]
echarts version 5.4.3
echarts-wordcloud version 2.1.0
![微信截图_20240315110808](https://github.com/ecomfe/echarts-wordcloud/assets/43006136/cb1bc7c5-2053-4fe4-aca4-eddb1af1fb93)

**Comment by lingdan33** [comment]
请问这个问题你怎么解决的，我现在引入进来也是这样
