### ISSUE TITLE
怎样通过import命令引入

### ISSUE THREAD

**Issue by iamwelk** [ecomfe/echarts-wordcloud#19]
怎样通过`import`命令引入插件并使用？

![image](https://cloud.githubusercontent.com/assets/6983075/25223064/e915883c-25ec-11e7-8209-cb9f1b24fd1b.png)
![image](https://cloud.githubusercontent.com/assets/6983075/25223074/ef016270-25ec-11e7-82d7-6b91dc222ccb.png)

在项目中使用的`vue-echarts-v3`，导入插件后提示`wordCloud`不存在

**Comment by iamwelk** [comment]
是可以用的，只不过vue-echarts-v3不支持，换了vue-echarts之后就可以了

**Comment by lustlost** [comment]
@iamwelk 
我也出现了这个问题，不过换了vue-echarts也报同样的错误，能不能看下你的用法

**Comment by iamwelk** [comment]
![image](https://user-images.githubusercontent.com/6983075/28955028-c12ce1f4-7915-11e7-905b-73daae574816.png)

**Comment by lustlost** [comment]
@iamwelk 能贴一下你在用的 echarts echarts-wordcloud vue-echarts这几个模块的版本么

**Comment by lustlost** [comment]
@iamwelk 很神奇的好了...之前配的和你差不多...有可能哪里少了个字符

**Comment by DangDangHellen** [comment]
![image](https://user-images.githubusercontent.com/23217362/53065563-21d28a00-3507-11e9-8956-caa1ebc8cb8d.png)
为什么报下面的错误：
[Vue warn]: Error in callback for watcher "options": "Error: Component series.wordCloud not exists. Load it first."
