### ISSUE TITLE
不支持词云textStyle.normal.color,设置颜色

### ISSUE THREAD

**Issue by guanxf** [ecomfe/echarts-wordcloud#37]
引用3.7.0版本的echarts，不支持词云textStyle.normal.color设置颜色

**Comment by bindai** [comment]
+1 我也遇到了同样的问题

**Comment by bindai** [comment]
![904b52a4-fd40-42e3-8ece-b840890d7440](https://user-images.githubusercontent.com/5703598/29708563-9b981a7e-89bb-11e7-87a7-d0f3ee9d2733.png)
 
颜色可以正常显示 但是字重叠了， gridSize设成20 也没什么用 （之前字并不重叠，只是颜色都是黑色）

![e815115b-1ac5-4d94-818f-963785fce088](https://user-images.githubusercontent.com/5703598/29708616-d8960062-89bb-11e7-9bcd-fda1281f0047.png)
