### ISSUE TITLE
使用版本1.1.1， 字符重叠

### ISSUE THREAD

**Issue by bindai** [ecomfe/echarts-wordcloud#38]
![f2031e4d-a9d3-4059-9ec1-9cf004681f6f](https://user-images.githubusercontent.com/5703598/29757780-0309a160-8be1-11e7-925e-2d0151f5e447.png)

**Comment by ivan706** [comment]
![image](https://user-images.githubusercontent.com/4433047/29761708-2fe99ba6-8bfd-11e7-8f7f-77afa2cbe22c.png)
使用官方例子，加了几个单词后也会出现覆盖
![image](https://user-images.githubusercontent.com/4433047/29761771-78d52844-8bfd-11e7-8549-425a6a674ddd.png)

**Comment by bindai** [comment]
这个什么时候能修复呢  在线等

**Comment by KJin9** [comment]
这个问题我也出现了！跪求

**Comment by Stupidism** [comment]
@pissang 非常严重的bug,整个项目可以说不能用了.  尝试了各种版本组合都不行. 貌似只有你们自己gh-pages里面那种html的写法可行. 用import 'echarts'这样的字符都在重叠...

**Comment by pissang** [comment]
1.1.2 中已修复重叠的问题，抱歉拖了这么久给大家造成了困扰

**Comment by mrlionline** [comment]
![image](https://user-images.githubusercontent.com/20840019/82191072-85519000-98e1-11ea-8a2c-7c40ebdc1bc2.png)
1.1.3版本依旧有此问题，360极速浏览器大概率复现，chrome 81.0.4044.138（正式版本） （64 位）小概率复现，windows 10系统
