### ISSUE TITLE
如何给图例加虚线？

### ISSUE THREAD

**Issue by Spring-Chang** [ecomfe/echarts-wordcloud#65]
图例legend如何改变样式？例如改为：点点点形式....,横杆横杆形式----,点横杆点横杆.-.-形式？我知道echarts的折线可以加上这些，现在组长要求给图例也加上！

**Comment by bltsheep** [comment]
同问，我也需要在图例上用虚线。

**Comment by Spring-Chang** [comment]
无答案

**Comment by LuoHongXin** [comment]
可以通过legend里的icon属性，将图标设置为任意的矢量路径'path://' ，例如直线："path://M6 4L30 4L30 8L6 8"，而虚线无非就是多条短的直线:"path://M6 5L8 5L8 6L6 6ZM9 5L11 5L11 6L9 6ZM12 5L14 5L14 6L12 6Z"，类似直线、虚线、圆形等简单的图形我们都可以直接自己写矢量路径，如果是复杂的图案，你可以叫UI或则自己去用 [svg工具](url=https://c.runoob.com/more/svgeditor/#delete)画一个，然后自己提取path路径。
