### ISSUE TITLE
使用echart的setOption进行重绘，重绘图和原图重合

### ISSUE THREAD

**Issue by Cyycl** [ecomfe/echarts-wordcloud#8]
已经设置setOption函数的notMerge参数为true

**Comment by FlowerBirds** [comment]
貌似现在的版本中还是存在重合现象，我都是在setOption前调用chart.clear()，然后全部更新notMerge为true，这样的话不会出现前后两次重叠现象。重合现象会出现在调用更新值间隔较短时，前一次绘制还未完成，下一次绘制已经开始，而上一次的绘制没有被中断，故会两次效果叠加。我已经试了很多次了，版本wordcloud-1.0.2

**Comment by pissang** [comment]
同 https://github.com/ecomfe/echarts-wordcloud/issues/12 ， 已修复

**Comment by amily4555** [comment]
我用最新的 1.1.2 但这个问题还在

**Comment by buctwbzs** [comment]
1.1.3存在
