### ISSUE TITLE
echarts.graphic.setTextStyle is not a function

### ISSUE THREAD

**Issue by DUMUUZEEJIA** [ecomfe/echarts-wordcloud#92]
at Object.seriesModel.layoutInstance.ondraw(WordCloudVIew.js:25)
at HTMLCanvasElement.onWordCloudDrawn(wordCloud.js:137)

**Comment by Luning644182206** [comment]
我也遇到了这个问题，您解决了吗？

**Comment by Luning644182206** [comment]
我下载了4.2.1的版本解决了这个问题，应该是echarts迭代导致的，之前用的是4.4.4

**Comment by frienkiss** [comment]
同问：5.x版本会报此错误，并且水球图echarts-liquidfill.min.js也会报错

**Comment by pissang** [comment]
wordcloud 和 echarts 都更新到最新版本呢
